CREATE TABLE notifications (
	id BIGSERIAL PRIMARY KEY,
	activity_id BIGSERIAL REFERENCES activities(id) ON DELETE CASCADE,
	actor_id BIGSERIAL REFERENCES actors(id) ON DELETE CASCADE,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
