CREATE TABLE notifications (
	id BIGSERIAL PRIMARY KEY,
	activity_id BIGSERIAL REFERENCES activities(id),
	actor_id BIGSERIAL REFERENCES actors(id),
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
